version: 2

registries:
  docker-registry-registry-hub-docker-com:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: lifendependabot
    password: "${{secrets.DOCKER_REGISTRY_REGISTRY_HUB_DOCKER_COM_PASSWORD}}"


updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "05:00"
    timezone: Europe/Paris
    day: monday
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "05:00"
    timezone: Europe/Paris
    day: monday
  registries:
  - docker-registry-registry-hub-docker-com
